from __future__ import annotations

import pandas as pd

EXERCISES = pd.DataFrame(
    [
        {
            "exercise_id": "ex-login-001",
            "module": "软件测试",
            "difficulty": "基础",
            "cohort_id": "jhc-2026-java",
            "related_task": "登录功能测试用例",
            "scenario": "JHC Java新人训练营正在测试 Spring Boot + Thymeleaf 登录画面。学员已经写了正常登录、错误密码、空用户名三条用例，但还缺业务边界。",
            "question_type": "单选题",
            "question": "下面哪一组测试用例最能补充登录功能的业务边界？",
            "options": [
                "A. 只测试正确用户名、正确密码、点击登录按钮。",
                "B. 只测试错误密码、空用户名、空密码。",
                "C. 覆盖角色权限、连续失败锁定、特殊字符、超长输入、空格处理、登录后跳转。",
                "D. 只测试页面颜色、按钮大小、Logo 是否显示。",
            ],
            "correct_option": "C",
            "explanation": "登录测试不能只覆盖正常/错误输入，还要覆盖权限、异常输入、安全边界和页面流转。",
            "required_output": "选择最合适的测试覆盖方案；可选填写补充说明。",
            "hint": "不要只写输入正确/错误，要考虑用户角色、异常输入和登录后的页面流转。",
            "golden_solution": "正确方向：管理员登录后进入管理菜单；普通用户不能进入管理菜单；连续5次错误密码后账号临时锁定；用户名含特殊字符时提示格式错误；超长用户名不应导致页面异常；首尾空格应被处理或提示；登录成功后跳回原访问页面。",
            "rubric": "选择正确80%；补充说明能指出权限/异常/安全/跳转边界20%。",
        },
        {
            "exercise_id": "ex-order-002",
            "module": "业务分析",
            "difficulty": "中级",
            "cohort_id": "jhc-2026-java",
            "related_task": "订单状态流转拆解",
            "scenario": "培训管理系统中，一个订单可能经历未支付、已支付、部分退费、结转、课耗扣减、跨校区结算。客户希望新人能说清楚状态流转。",
            "question_type": "单选题",
            "question": "订单状态流转分析时，哪一个选项最完整？",
            "options": [
                "A. 只需要说明未支付和已支付两个状态。",
                "B. 只需要说明订单金额，不需要说明课次和课耗。",
                "C. 需要说明创建、支付、上课扣课耗、余额变化、结课/结转，并覆盖重复支付、退费、课耗回滚、跨校区结算等异常。",
                "D. 只需要画一个从创建到完成的直线流程。",
            ],
            "correct_option": "C",
            "explanation": "订单分析必须同时覆盖钱、课次、余额、课耗、退费、结转和跨校区结算，否则业务风险很大。",
            "required_output": "选择最合适的订单状态流转分析方案；可选填写补充说明。",
            "hint": "重点看钱、课次、余额、课耗、校区结算是否一致。",
            "golden_solution": "主流程：创建订单→未支付→已支付→上课扣课耗→余额变化→结课/结转。异常：重复支付、支付后退费、退费后课耗回滚、结转后再次退费、跨校区结算状态不一致、订单已结清但仍排课。",
            "rubric": "选择正确75%；补充说明能指出资金/课次/课耗/结算一致性25%。",
        },
        {
            "exercise_id": "ex-jpqa-003",
            "module": "日语发表",
            "difficulty": "基础",
            "cohort_id": "jhc-2026-java",
            "related_task": "日语Q&A发表准备",
            "scenario": "结业发表会上，对方公司领导可能会问到学生不知道的问题。学生需要用自然、礼貌、职业化的日语回答。",
            "question_type": "单选题",
            "question": "发表会 Q&A 中，遇到自己无法准确回答的问题，最合适的日语回答是哪一个？",
            "options": [
                "A. たぶん大丈夫だと思います。詳しくは分かりません。",
                "B. それは私の担当ではありません。",
                "C. 申し訳ありません。現時点では正確にお答えできないため、確認してから後ほど回答いたします。",
                "D. すみません、次の質問をお願いします。",
            ],
            "correct_option": "C",
            "explanation": "不知道时不能乱编，也不能推开问题。应先道歉、说明需要确认、承诺后续回答。",
            "required_output": "选择最合适的日语回答；可选填写中文说明。",
            "hint": "不要硬编答案。重点是诚实、确认、后续补充。",
            "golden_solution": "申し訳ありません。現時点では正確にお答えできないため、確認してから後ほど回答いたします。／補足として、発表後に担当者を通じて共有いたします。",
            "rubric": "选择正确80%；补充说明能体现诚实、确认、后续补充20%。",
        },
        {
            "exercise_id": "ex-bug-004",
            "module": "错误定位",
            "difficulty": "中级",
            "cohort_id": "jhc-2026-java",
            "related_task": "Spring Boot错误定位报告",
            "scenario": "Controller 调用 Service 后，页面没有显示查询结果。日志提示 MyBatis 参数绑定失败。",
            "question_type": "单选题",
            "question": "面对 MyBatis 参数绑定失败，最优先排查哪一组内容？",
            "options": [
                "A. 只检查页面 CSS 是否加载。",
                "B. 只重启服务器，看问题是否消失。",
                "C. 检查 Controller 参数、Service 方法、Mapper 接口 @Param、Mapper XML 中的占位符名称是否一致。",
                "D. 直接删除 Mapper XML 重新生成。",
            ],
            "correct_option": "C",
            "explanation": "MyBatis 参数绑定失败通常和参数名、@Param、XML 占位符、DTO 字段不一致有关。",
            "required_output": "选择最合适的排查方向；可选填写补充说明。",
            "hint": "注意 Controller 参数名、Mapper XML 参数名、DTO字段名是否一致。",
            "golden_solution": "可能原因为 Mapper XML 中 #{userId} 与方法参数 @Param('id') 不一致。确认方法：查看接口签名、XML、日志参数名。修复：统一命名或补 @Param。验证：重启后查询成功，并补正常/异常测试。",
            "rubric": "选择正确75%；补充说明能写出确认步骤和验证方法25%。",
        },
        {
            "exercise_id": "ex-founder-005",
            "module": "Founder运营",
            "difficulty": "中级",
            "cohort_id": "jhc-2026-java",
            "related_task": "Review Queue处理",
            "scenario": "鈴木美咲的订单状态流转拆解得分81，Agent认为结构较完整，但还缺重复支付和退费后课耗回滚。Founder需要决定是否进入 Proof Files。",
            "question_type": "单选题",
            "question": "Founder 当前最合理的处理决策是哪一个？",
            "options": [
                "A. 直接确认进入 Proof Files，因为已经超过80分。",
                "B. 直接删除该提交。",
                "C. 标记为候选并要求小修，补充重复支付、退费后课耗回滚、跨校区结算影响后再进入 Proof Files。",
                "D. 完全不反馈，让学员自己猜。",
            ],
            "correct_option": "C",
            "explanation": "81分说明具备候选基础，但缺关键异常分支时不应直接进入客户可见证明。",
            "required_output": "选择最合理 Founder 决策；可选填写反馈说明。",
            "hint": "81分不一定直接通过。看是否已经达到客户汇报/面试展示标准。",
            "golden_solution": "建议标记为候选并打回小修：主流程完整，具备展示基础；但必须补重复支付、退费后课耗回滚、跨校区结算影响。完成后可进入 Proof Files。",
            "rubric": "选择正确75%；补充说明能体现证明标准和下一步动作25%。",
        },
        {
            "exercise_id": "ex-lead-006",
            "module": "服务包销售",
            "difficulty": "高级",
            "cohort_id": "jhc-2026-java",
            "related_task": "Java新人训练标准包线索",
            "scenario": "信华信日本业务部对 3 个月 Java 新人训练满意，希望了解能否沉淀成标准包，减少每年重复沟通和讲师依赖。",
            "question_type": "单选题",
            "question": "面对这个线索，最好的服务包表达是哪一个？",
            "options": [
                "A. 单纯卖更多 Java 课时，按天报价即可。",
                "B. 告诉客户未来不用培训了，AI 可以全部替代。",
                "C. 设计 Java 新人研修 Proof Sprint：任务卡、样例答案、Agent Review 标准、Founder 周报、学员 Proof Files，先做5天样板再扩展到3个月。",
                "D. 只发一份通用公司介绍，不谈交付物。",
            ],
            "correct_option": "C",
            "explanation": "客户要的是减少重复沟通和讲师依赖，所以要卖标准任务包、评审标准、证明文件和运营看板。",
            "required_output": "选择最合适的服务包方案；可选填写商业理由。",
            "hint": "不要卖课时，要卖任务包、点评标准、作品证明和运营看板。",
            "golden_solution": "方案：Java新人研修 Proof Sprint，包含任务卡、样例答案、Agent Review标准、Founder周报、学员Proof Files。周期5天样板+3个月扩展，报价78000元。客户收益：降低重复培训设计成本、统一新人输出标准、沉淀可复用资产。",
            "rubric": "选择正确70%；补充说明能体现客户痛点、交付物和转化路径30%。",
        },
        {
            "exercise_id": "ex-proof-007",
            "module": "作品证明",
            "difficulty": "基础",
            "cohort_id": "jhc-2026-java",
            "related_task": "Skill Proof File整理",
            "scenario": "山本結衣已经完成 Spring Boot 错误定位报告，Founder准备把它加入客户汇报材料。",
            "question_type": "单选题",
            "question": "整理 Skill Proof File 时，哪种结构最适合客户判断能力？",
            "options": [
                "A. 只写：我修好了。",
                "B. 只贴一张截图，不说明过程。",
                "C. 背景、方法、结果、证据、复盘，说明问题、排查路径、修复结果和可验证材料。",
                "D. 只写学员很努力。",
            ],
            "correct_option": "C",
            "explanation": "Proof File 要让别人判断能力，必须包含背景、方法、结果、证据和复盘。",
            "required_output": "选择最合适的 Proof File 结构；可选填写补充说明。",
            "hint": "不要只写'修好了'，要留下别人能判断能力的证据。",
            "golden_solution": "背景：页面查询无结果；方法：检查日志、Controller、Service、Mapper XML；结果：发现参数名不一致并修复；证据：错误日志、修正前后截图、测试结果；复盘：参数命名规范和测试覆盖。",
            "rubric": "选择正确80%；补充说明能体现证据和复盘价值20%。",
        },
        {
            "exercise_id": "ex-trainer-008",
            "module": "培训产品化",
            "difficulty": "高级",
            "cohort_id": "bitkids-mentor-01",
            "related_task": "讲师交付能力训练包",
            "scenario": "比特顽童教育希望降低新讲师培养成本。过去依赖老讲师口头带新人，质量不稳定。",
            "question_type": "单选题",
            "question": "为了降低新讲师培养成本，最适合产品化的方案是哪一个？",
            "options": [
                "A. 继续完全依赖老讲师口头带新人。",
                "B. 只给新讲师一本教材，不做过程记录。",
                "C. 建立讲师交付能力训练包：试听课演练任务卡、课堂问题处理Q&A、家长沟通模板、课程复盘表、Founder点评队列、讲师 Proof Files。",
                "D. 只要求新讲师自己看视频学习。",
            ],
            "correct_option": "C",
            "explanation": "产品化的关键是把经验变成任务卡、模板、点评标准、证据和运营看板，而不是继续靠口头传授。",
            "required_output": "选择最合适的讲师训练包方案；可选填写商业理由。",
            "hint": "从讲师劳动变成可复制任务系统，而不是只卖培训天数。",
            "golden_solution": "服务包包含：试听课演练任务卡、课堂问题处理Q&A、家长沟通模板、课程复盘表、Founder点评队列、讲师Proof Files。报价可按样板包24000元起。",
            "rubric": "选择正确70%；补充说明能体现产品化、任务系统和运营闭环30%。",
        },
    ]
)


def get_exercise_metrics() -> dict[str, int]:
    return {
        "exercise_count": int(len(EXERCISES)),
        "module_count": int(EXERCISES["module"].nunique()),
        "basic_count": int((EXERCISES["difficulty"] == "基础").sum()),
        "advanced_count": int((EXERCISES["difficulty"] == "高级").sum()),
        "mcq_count": int((EXERCISES["question_type"] == "单选题").sum()),
    }
