from __future__ import annotations

import pandas as pd

EXERCISES = pd.DataFrame(
    [
        {
            "exercise_id": "ex-login-001",
            "module": "软件测试",
            "difficulty": "基础",
            "cohort_id": "jhc-2026-java",
            "related_task": "登录功能测试用例",
            "scenario": "JHC Java新人训练营正在测试 Spring Boot + Thymeleaf 登录画面。学员已经写了正常登录、错误密码、空用户名三条用例，但还缺业务边界。",
            "question": "请补充 6 条登录功能测试用例，必须覆盖：权限差异、连续失败、特殊字符、超长输入、空格处理、登录后跳转。",
            "required_output": "测试用例表：用例编号、前置条件、输入、操作步骤、预期结果、优先级。",
            "hint": "不要只写输入正确/错误，要考虑用户角色、异常输入和登录后的页面流转。",
            "golden_solution": "示例方向：管理员登录后进入管理菜单；普通用户不能进入管理菜单；连续5次错误密码后账号临时锁定；用户名含特殊字符时提示格式错误；超长用户名不应导致页面异常；首尾空格应被处理或提示；登录成功后跳回原访问页面。",
            "rubric": "覆盖面40%；步骤清晰25%；预期结果可验证25%；优先级合理10%。",
        },
        {
            "exercise_id": "ex-order-002",
            "module": "业务分析",
            "difficulty": "中级",
            "cohort_id": "jhc-2026-java",
            "related_task": "订单状态流转拆解",
            "scenario": "培训管理系统中，一个订单可能经历未支付、已支付、部分退费、结转、课耗扣减、跨校区结算。客户希望新人能说清楚状态流转。",
            "question": "请画出订单状态流转，并列出至少 5 个异常分支。",
            "required_output": "状态流转说明 + 异常分支表：触发条件、系统处理、影响数据、需要提示。",
            "hint": "重点看钱、课次、余额、课耗、校区结算是否一致。",
            "golden_solution": "主流程：创建订单→未支付→已支付→上课扣课耗→余额变化→结课/结转。异常：重复支付、支付后退费、退费后课耗回滚、结转后再次退费、跨校区结算状态不一致、订单已结清但仍排课。",
            "rubric": "主流程完整30%；异常分支完整35%；数据影响清楚25%；业务语言准确10%。",
        },
        {
            "exercise_id": "ex-jpqa-003",
            "module": "日语发表",
            "difficulty": "基础",
            "cohort_id": "jhc-2026-java",
            "related_task": "日语Q&A发表准备",
            "scenario": "结业发表会上，对方公司领导可能会问到学生不知道的问题。学生需要用自然、礼貌、职业化的日语回答。",
            "question": "请写出 5 个质疑场景下的日语回答，包括：不知道答案、需要确认、被指名回答、回答不完整、会后补充。",
            "required_output": "Q&A表：问题场景、日语回答、中文解释、注意点。",
            "hint": "不要硬编答案。重点是诚实、确认、后续补充。",
            "golden_solution": "例：申し訳ありません。現時点では正確にお答えできないため、確認してから後ほど回答いたします。／補足として、発表後に担当者を通じて共有いたします。",
            "rubric": "日语自然度35%；商务礼貌25%；场景覆盖25%；不乱编答案15%。",
        },
        {
            "exercise_id": "ex-bug-004",
            "module": "错误定位",
            "difficulty": "中级",
            "cohort_id": "jhc-2026-java",
            "related_task": "Spring Boot错误定位报告",
            "scenario": "Controller 调用 Service 后，页面没有显示查询结果。日志提示 MyBatis 参数绑定失败。",
            "question": "请写一份错误定位报告，说明可能原因、确认步骤、修复方案和验证方法。",
            "required_output": "错误定位报告：现象、日志、原因假设、排查步骤、修复、验证、复盘。",
            "hint": "注意 Controller 参数名、Mapper XML 参数名、DTO字段名是否一致。",
            "golden_solution": "可能原因为 Mapper XML 中 #{userId} 与方法参数 @Param('id') 不一致。确认方法：查看接口签名、XML、日志参数名。修复：统一命名或补 @Param。验证：重启后查询成功，并补正常/异常测试。",
            "rubric": "定位链路40%；修复方案25%；验证方法25%；复盘10%。",
        },
        {
            "exercise_id": "ex-founder-005",
            "module": "Founder运营",
            "difficulty": "中级",
            "cohort_id": "jhc-2026-java",
            "related_task": "Review Queue处理",
            "scenario": "鈴木美咲的订单状态流转拆解得分81，Agent认为结构较完整，但还缺重复支付和退费后课耗回滚。Founder需要决定是否进入 Proof Files。",
            "question": "请给出 Founder 决策：确认进入作品集、打回修改、还是标记为候选？说明理由和下一步动作。",
            "required_output": "Founder决策记录：决策、理由、给学员的反馈、下一步截止时间。",
            "hint": "81分不一定直接通过。看是否已经达到客户汇报/面试展示标准。",
            "golden_solution": "建议标记为候选并打回小修：主流程完整，具备展示基础；但必须补重复支付、退费后课耗回滚、跨校区结算影响。完成后可进入 Proof Files。",
            "rubric": "决策合理35%；理由清楚30%；反馈可执行25%；时间要求10%。",
        },
        {
            "exercise_id": "ex-lead-006",
            "module": "服务包销售",
            "difficulty": "高级",
            "cohort_id": "jhc-2026-java",
            "related_task": "Java新人训练标准包线索",
            "scenario": "信华信日本业务部对 3 个月 Java 新人训练满意，希望了解能否沉淀成标准包，减少每年重复沟通和讲师依赖。",
            "question": "请设计一个 Java 新人训练标准包报价摘要，包含目标、交付物、周期、价格、客户收益和下一步。",
            "required_output": "服务包方案摘要：客户痛点、服务内容、交付物、价格、实施周期、下一步CTA。",
            "hint": "不要卖课时，要卖任务包、点评标准、作品证明和运营看板。",
            "golden_solution": "方案：Java新人研修 Proof Sprint，包含任务卡、样例答案、Agent Review标准、Founder周报、学员Proof Files。周期5天样板+3个月扩展，报价78000元。客户收益：降低重复培训设计成本、统一新人输出标准、沉淀可复用资产。",
            "rubric": "客户痛点准确25%；交付物具体30%；价格和周期清楚20%；转化话术25%。",
        },
        {
            "exercise_id": "ex-proof-007",
            "module": "作品证明",
            "difficulty": "基础",
            "cohort_id": "jhc-2026-java",
            "related_task": "Skill Proof File整理",
            "scenario": "山本結衣已经完成 Spring Boot 错误定位报告，Founder准备把它加入客户汇报材料。",
            "question": "请把该作品整理成 Skill Proof File 的四段结构：背景、方法、结果、复盘。",
            "required_output": "Skill Proof File：背景、方法、结果、证据、复盘。",
            "hint": "不要只写'修好了'，要留下别人能判断能力的证据。",
            "golden_solution": "背景：页面查询无结果；方法：检查日志、Controller、Service、Mapper XML；结果：发现参数名不一致并修复；证据：错误日志、修正前后截图、测试结果；复盘：参数命名规范和测试覆盖。",
            "rubric": "结构完整30%；证据明确30%；复盘有价值25%；表达清晰15%。",
        },
        {
            "exercise_id": "ex-trainer-008",
            "module": "培训产品化",
            "difficulty": "高级",
            "cohort_id": "bitkids-mentor-01",
            "related_task": "讲师交付能力训练包",
            "scenario": "比特顽童教育希望降低新讲师培养成本。过去依赖老讲师口头带新人，质量不稳定。",
            "question": "请设计一个讲师交付能力训练包，说明任务卡、点评标准、作品集模板和运营看板。",
            "required_output": "产品化服务包：目标客户、核心任务、交付物、运营流程、报价建议。",
            "hint": "从讲师劳动变成可复制任务系统，而不是只卖培训天数。",
            "golden_solution": "服务包包含：试听课演练任务卡、课堂问题处理Q&A、家长沟通模板、课程复盘表、Founder点评队列、讲师Proof Files。报价可按样板包24000元起。",
            "rubric": "产品化程度35%；任务设计30%；运营闭环20%；报价逻辑15%。",
        },
    ]
)


def get_exercise_metrics() -> dict[str, int]:
    return {
        "exercise_count": int(len(EXERCISES)),
        "module_count": int(EXERCISES["module"].nunique()),
        "basic_count": int((EXERCISES["difficulty"] == "基础").sum()),
        "advanced_count": int((EXERCISES["difficulty"] == "高级").sum()),
    }
